#!/bin/bash

sudo apt-get remove -y libreoffice-common
sudo apt-get remove -y unity-webapps-common
sudo apt-get remove -y thunderbird totem rhythmbox empathy brasero simple-scan gnome-mahjongg aisleriot gnome-mines cheese transmission-common gnome-orca webbrowser-app gnome-sudoku landscape-client-ui-install
sudo apt-get remove -y onboard deja-dup

sudo apt-get install -y python-dev python-pip libxml2-dev libxslt1-dev zlib1g-dev libffi-dev libssl-dev
sudo pip install -y scrapy
sudo apt-get install -y libzmq-dev
sudo pip install -y pyzmq #here
sudo pip install -y pygments
sudo apt-get install -y qt4-dev-tools qt4-doc qt4-qtconfig qt4-demos qt4-designer
sudo pip install -y qtconsole
sudo pip install -y ipython

sudo apt install -y spyder


sudo apt install -y octave

sudo apt-get install -y default-jre
sudo apt-get install -y default-jdk

sudo apt-get install -y g++ vim geany


sudo add-apt-repository ppa:damien-moore/codeblocks-stable
sudo add-apt-repository ppa:webupd8team/sublime-text-3
sudo add-apt-repository ppa:webupd8team/atom
sudo wget http://www.linuxidc.com/files/repo/google-chrome.list -P /etc/apt/sources.list.d/
wget -q -O - https://dl.google.com/linux/linux_signing_key.pub  | sudo apt-key add -
sudo apt-get update
sudo apt-get install -y sublime-text-installer
sudo apt install codeblocks -y codeblocks-contrib atom
sudo apt-get install -y google-chrome-stable


sudo apt-get -y install -y build-essential cmake valgrind
sudo apt-get install -y openssh-server
sudo ufw allow 22

